### PR TITLE
little things

### PR DESCRIPTION
**Pull request by ngoldman**
added readme, contributing guidelines, `.travis.yml`

guessing we're targeting io.js only for tests for now

### CODE REVIEW

**Comment by ngoldman** [comment]
rebasing...

**Comment by shama** [comment]
Oops sorry!

**Comment by ngoldman** [comment]
@shama np, rebased!

**Comment by ngoldman** [comment]
@feross want to enable travis-ci to auto-run standard & future tests on PRs etc?

**Comment by ngoldman** [comment]
@shama reformatted your code a tiny bit to pass standard

**Comment by shama** [comment]
Thanks for the fixes!

**Comment by ngoldman** [comment]
@shama np! @feross is working on UI, are you still doing stuff in there? where's a good place to chat? IRC? we're in #dat

**Pull request merged**
